import type { Metadata } from "next";
import "./globals.css";
import Heading from "@/components/common/Heading";
import NavBar from "@/components/common/NavBar";

export const metadata: Metadata = {
    title: "Dashboard App",
    description: "Dashboard app by generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased h-screen`}>
                <Heading classHeading="h-1/7" />
                <article className="h-6/7 flex overflow-hidden">
                    <NavBar classNavBar="w-1/4 h-full bg-gray-100 shadow-md z-10" />
                    <div className="container overflow-y-auto">{children}</div>
                </article>
            </body>
        </html>
    );
}
