import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Heading from "@/components/common/Heading";
import NavBar from "@/components/common/NavBar";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Dashboard App",
    description: "Dashboard app by generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
            >
                <Heading classHeading="h-1/7" />
                <article className="h-6/7 flex overflow-hidden">
                    <NavBar classNavBar="w-1/4 h-full bg-gray-100 shadow-md z-10" />
                    <div className="container overflow-y-auto">{children}</div>
                </article>
            </body>
        </html>
    );
}
